### ISSUE TITLE
Updatemanager silently fails on plugin installation

### ISSUE THREAD

**Issue by nagelfargithub** [modular-mind/updatemanager#6]
Updating from a November 22nd client with the current UpdateManager Version to a current version gave some unexpected results in our logs:
```
06.12.2021 17:45:30.455 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Starting P2 auto-update process
06.12.2021 17:45:30.457 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Provisioning agent created
06.12.2021 17:45:30.872 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Provisioning session created
06.12.2021 17:45:32.102 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Metadata repository loaded: http://[our_server]
06.12.2021 17:45:32.624 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Artifact repository loaded: http://[our_server] 
06.12.2021 17:45:33.424 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Update operation resolved successfully
06.12.2021 17:45:33.424 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Possible updates:
06.12.2021 17:45:33.425 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   -  - Update klv-feature.feature.group 1.0.0.202111220852 ==> klv-feature.feature.group 1.0.0.202112061457
06.12.2021 17:45:33.439 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - IUs to install (possibly 259):
06.12.2021 17:45:33.440 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Found IU to install: org.eclipse.nebula.cwt.feature.feature.group
06.12.2021 17:45:33.440 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Found IU to install: org.eclipse.nebula.widgets.cdatetime.feature.feature.group
06.12.2021 17:45:33.838 [      main] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Install operation resolved successfully
06.12.2021 17:45:36.542 [dalContext] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Status OK: unknown code=0 OK null
06.12.2021 17:45:36.549 [dalContext] [INFO ]  c.e.klv.service.KLVUpdateManagerLogger   - Updates installed, restart required
06.12.2021 17:45:36.593 [      main] [INFO ]  com.evolit.klv.ui.LifeCycleManager       - no update necessary
```
What is strange is that the UpdateManagerLogger logs "Updates installed", restart required yet our LifeCycleManager thinks no updates are necessary. The code for the LifeCycleManager is straightforward:
```
		boolean updateDone = updateManager.performAutoUpdate();
		//close the splashscreen
		appContext.applicationRunning();
		if(updateDone) { 
			log.info("update was performed");
			eventBroker.subscribe(UIEvents.UILifeCycle.APP_STARTUP_COMPLETE, new ApplicationUpdateListener(context));
			final Shell shell = new Shell(SWT.INHERIT_NONE);
			MessageDialog.openInformation(shell, messages.label_restart, messages.msg_restart);
		} else {
			log.info("no update necessary");
		}
```
Feature that need to be updated and newly added plugins (nebula cdatetime etc) are correctly resolved but there seems to be an issue when installing them but no error is shown in the logs.

Further digging into things (starting the application with -consoleLog enabled led to this stacktrace:
```
java.lang.reflect.InvocationTargetException
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
        at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:469)
        at com.modumind.updatemanager.service.impl.UpdateManagerImpl.performAutoUpdate(UpdateManagerImpl.java:199)
        at com.evolit.klv.ui.LifeCycleManager.postContextCreate(LifeCycleManager.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:247)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:147)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.lambda$0(E4Application.java:246)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:242)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:153)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
Caused by: java.lang.IllegalStateException: Profile DefaultProfile is not current. Expected timestamp 1638868967289 but was 1638868960634.
        at org.eclipse.equinox.internal.p2.engine.SimpleProfileRegistry.lockProfile(SimpleProfileRegistry.java:865)
        at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:72)
        at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
        at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:181)
        at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:76)
        at com.modumind.updatemanager.service.impl.UpdateManagerImpl$1.run(UpdateManagerImpl.java:175)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

This looks a little like "bug, but not a bug" https://bugs.eclipse.org/bugs/show_bug.cgi?id=392818 but I don't yet understand exactly what is going on.

Other bugs with this or similar issues:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544273
https://bugs.eclipse.org/bugs/show_bug.cgi?id=511149

Another observation: after the first, failed update I run the client again, the update is skipped because the context variable JUSTUPDATED is set.
I then run the client a third time. The update now works and the client restarts with the new version. Unfortunately it doesn't work properly as apparently some jars are not properly replaced.

**Comment by modular-mind** [comment]
Thanks for the bug report :-) This is definitely related to applying both updates and installs in the same request. The problem makes sense as the update job changes the profile timestamp and then the install job uses the stale profile. I can reproduce this.

I've got  a few ideas about how to fix this, should know more tomorrow.

**Comment by modular-mind** [comment]
Just committed a fix. The update and install operations now run using the most current profile, even if another operation has already run. You might notice the progress dialog flicker briefly if both update and install operations are done. This is because the dialog is now opened once for each job.

**Comment by modular-mind** [comment]
Also, I fixed the logging to capture an exception if it occurs during the provisioning job process. There shouldn't be any more hidden exceptions like this.

**Comment by nagelfargithub** [comment]
I updated the UpdateManager and a new test-update I pushed performed as expected.
